from setuptools import setup, find_packages

setup(
    name="department-project-ii",
    version="0.1.0",
    description="Astrophysical simulation analysis using Rascas with Ramses and Gadget output",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "matplotlib>=3.5.0",
        "astropy>=5.0",
        "h5py>=3.0.0",
        "pandas>=1.3.0",
        "seaborn>=0.11.0",
        "plotly>=5.0.0",
        "pynbody>=1.0.0",
        "yt>=4.0.0",
        "tqdm>=4.62.0",
        "configparser>=5.0.0",
    ],
    python_requires=">=3.8",
    author="Department Project Team",
    author_email="",
    url="https://github.com/Supriyosaha1/Department_project-II",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Astronomy",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)